run: (run-arch "$(nix eval --impure --raw --expr 'builtins.currentSystem')")

run-aarch64: (run-arch "aarch64-linux")

run-arch guest:
  nix run .#microvms.$(nix eval --impure --raw --expr 'builtins.currentSystem').host.{{guest}}.guest.config.microvm.declaredRunner