fmt:
    find . -name "*.nix" | xargs alejandra
    cargo fmt

build profile="":
    cargo build {{profile}}

db-setup:
    mkdir -p db
    cargo sqlx database setup

update-sqlx:
    cargo sqlx prepare --workspace
