name: CI
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Setup the magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Format
        run: |
          nix develop --impure --command just fmt
          git diff --exit-code
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v8
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
      - name: Setup the magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build
        run: |
          nix build
